  ##图片相关配置
config:
  base_path: F:\\teemo
  pic: ${config.base_path}\\pic

logback:
  logdir: ${config.base_path}\\log
  appname: mshop
  ##打印输出等级
  level: info

jdbc:
  url: 192.168.1.11
  name: root
  password: root

redis:
  url: 192.168.1.242
  password: jbladmin123
